<?xml version="1.0" encoding="UTF-8"?>
<project name="Helbound_GameServer" default="dist" basedir=".">

	<property name="src" location="java" />
	<property name="lib" location="data/Server/lib" />
	<property name="build" location="build" />

	<target name="dist" depends="jar">
		<echo>Build complete. Server files at data/Server/</echo>
		<delete dir="classes" />
		<delete dir="${build}" />
		<echo>Temp directories cleaned.</echo>
	</target>

	<target name="jar" depends="compile" description="Create the jar file.">
		<jar destfile="${build}/l2jserver.jar">
			<fileset dir="classes" />
			<manifest>
				<attribute name="Main-Class" value="net.sf.l2j.Server" />
				<attribute name="Class-Path" value="${manifest.libs}" />
			</manifest>
		</jar>
		<copy todir="data/Server/">
			<fileset dir="${build}">
				<include name="l2jserver.jar" />
			</fileset>
		</copy>
	</target>

	<target name="compile" depends="clean,init" description="Compile the source.">
		<javac srcdir="${src}" classpathref="classpath" destdir="classes" compiler="modern" debug="true" debuglevel="lines,vars,source" includeantruntime="false" source="25" target="25" encoding="UTF-8" />
	</target>
	
	<target name="init" depends="checkRequirements" description="Create the output directories.">
		<mkdir dir="${build}" />
		<mkdir dir="classes" />
	</target>

	<target name="clean" description="Remove the output directories.">
		<delete dir="${build}" />
		<delete dir="classes" />
	</target>

	<target name="checkRequirements" description="Check requirements.">
		<available classname="java.lang.ScopedValue" property="JDK25.present" />
		<fail unless="JDK25.present" message="Java 25 is required, but your version is Java ${ant.java.version}. Install JDK 25." />
	</target>
	
	<path id="classpath">
		<fileset dir="${lib}">
			<include name="*.jar" />
		</fileset>
	</path>

	<pathconvert property="manifest.libs" pathsep=" ">
		<path refid="classpath" />
		<mapper>
			<chainedmapper>
				<flattenmapper />
				<globmapper from="*.jar" to="lib/*.jar" />
			</chainedmapper>
		</mapper>
	</pathconvert>
	
</project>